### ISSUE TITLE
ToDo:

### ISSUE THREAD

**Issue by fhirt** [fhirt/python-xunit#1]
- [x] support should_
- [x] detailed TestResults -> record failure reason
- [x] TestReport collects -> TestResults
- [x] TestReportFormatter -> displays detailed TestReport
- [x] TestRunner runs multiple TestSuites
- [x] Assertions in the form of expect(value).toBe(expectedValue)
- [x] ~~TestReport displays the name of the TestSuite~~ TestResult contains name of TestCase and Report prints it out as well
- [x] ~~Composite of TestSuite - Suite of Suites~~ not needed
- [ ] TestRunner discovers TestCases in test-folder
